module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [{
      name: 'Aleks',
      surname: 'Umnov',
      email: 'Aleks@gmail.com',
      password: '123456',
      isAdmin: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Ivan',
      surname: 'Umnov',
      email: 'Ivan@gmail.com',
      password: '123456',
      isAdmin: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Nikita',
      surname: 'Umnov',
      email: 'Nikita@gmail.com',
      password: '123456',
      isAdmin: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Katya',
      surname: 'Umnova',
      email: 'Katya@gmail.com',
      password: '123456',
      isAdmin: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Kolya',
      surname: 'Umnov',
      email: 'Kolya@gmail.com',
      password: '123456',
      isAdmin: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Sasha',
      surname: 'Umnov',
      email: 'Sasha@gmail.com',
      password: '123456',
      isAdmin: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Dima',
      surname: 'Umnov',
      email: 'Dima@gmail.com',
      password: '123456',
      isAdmin: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Roma',
      surname: 'Umnov',
      email: 'Roma@gmail.com',
      password: '123456',
      isAdmin: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Sveta',
      surname: 'Umnova',
      email: 'Sveta@gmail.com',
      password: '123456',
      isAdmin: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      name: 'Fedor',
      surname: 'Umnov',
      email: 'Fedor@gmail.com',
      password: '123456',
      isAdmin: false,
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
