module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Points', [{
      trackId: 1,
      latitude: '59.91407',
      longitude: '29.78394',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 1,
      latitude: '59.86137',
      longitude: '30.11833 ',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 2,
      latitude: '60.00482',
      longitude: '129.99336',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 2,
      latitude: '59.98834',
      longitude: '30.17052',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 3,
      latitude: '59.94057',
      longitude: '30.31815',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 3,
      latitude: '59.94435',
      longitude: '130.39505',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 4,
      latitude: '59.91786',
      longitude: '30.3978',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 4,
      latitude: '59.85757',
      longitude: '30.47539',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 5,
      latitude: '59.87067',
      longitude: '30.17464',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 5,
      latitude: '59.86792',
      longitude: '29.9968',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 6,
      latitude: '59.95845',
      longitude: '30.336',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 6,
      latitude: '59.92285',
      longitude: '30.4081',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 7,
      latitude: '59.90771',
      longitude: '30.41805',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 7,
      latitude: '59.86999',
      longitude: '30.45788',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 8,
      latitude: '59.99143',
      longitude: '30.22476',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 8,
      latitude: '60.01683',
      longitude: '29.73312',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 9,
      latitude: '59.99487',
      longitude: '29.75922',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 9,
      latitude: '59.93575',
      longitude: '29.60266',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 10,
      latitude: '59.89031',
      longitude: '30.52551',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      trackId: 10,
      latitude: '59.90684',
      longitude: '31.00891',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Points', null, {});
  },
};
